### PR TITLE
Fixes #204: Exclude deploy directory in the codebase root.

### LINKED ISSUE #204: Difficulty in use with BLT: audit:list command scans deploy directory and throws fatals about class redeclaration
Drutiny: 2.2.2

Setting up Drutiny 2.2.2 with a [BLT](https://github.com/acquia/blt) project today I found that running `audit:list` was throwing fatals about a class in the migrate module being redeclared.

```
$ vendor/bin/drutiny audit:list
PHP Fatal error:  Cannot declare class Drupal\migrate\Audit\AuditResult, because the name is already in use in /Users/barrett.smith/Desktop/datasmith/docroot/core/modules/migrate/src/Audit/AuditResult.php on line 11

Fatal error: Cannot declare class Drupal\migrate\Audit\AuditResult, because the name is already in use in /Users/barrett.smith/Desktop/datasmith/docroot/core/modules/migrate/src/Audit/AuditResult.php on line 11
```
The problem turned out to be that the class existed in both the docroot directory and the [deploy directory, which is where BLT builds code artifacts for deployment](https://blt.readthedocs.io/en/latest/deploy/). Drutiny is apparently scanning both locations, hence the fatals about the class being redeclared.

I haven't dug into the mechanics yet, but perhaps Drutiny could detect if BLT is also in use on a project and ignore the `deploy` directory if so? I'll dig in and submit a PR once I sort it out.

### PR DESCRIPTION
**Pull request by ba66e77**

### CODE REVIEW

**Comment by fiasco** [comment]
Where did the deploy dir come from?

**Comment by ba66e77** [comment]
It's created by the BLT project when it generates a build artifact.

**Comment by fiasco** [comment]
Happy to accept the PR but note that running Drutiny in a standalone environment is prefered as it otherwise requires mixing dependencies of Drutiny with BLT and Drupal which may lead to composer pain.

**Comment by ba66e77** [comment]
Ah, I was not aware of that recommendation. If that's the preferred approach, then this PR is probably a moot point and can be reverted

**Pull request merged**
