### PR TITLE
No closing php tags

### PR DESCRIPTION
**Pull request by simesy**

### CODE REVIEW

**Comment by fiasco** [comment]
```
$ find . -name \*.php -exec tail -1 {} \; | sort | uniq -c | grep \?
  49  ?>
   4 ?>
```
This PR ought to address all `.php` files rather than just one.

**Comment by simesy** [comment]
Ah I wasn't aware. So does the whole thing need a lint then?

**Comment by fiasco** [comment]
There isn't anything syntactically wrong with php tags at the end of file right?

> So does the whole thing need a lint then?

Yeah probably.

**Comment by simesy** [comment]
nw. I just did this fix through the github UI but when i have the code open i'll have a look.

**Comment by simesy** [comment]
It's optional, but considered best practice because whitespace after the `?>` can cause early headers to be sent to the browser. Not going to effect this, it would just send some whitespace to the buffer (I guess) in a CLI situation. But yes, generally considered best practice.

**Pull request closed without merging**
