### PR TITLE
Make D7 GA check more helpful. Fixes #81.

### LINKED ISSUE #81: D7 GA check unhelpful
Hi.
Your tool is included in the site audit for govCMS. While running those checks on a site that had no special GA configuration, I received the D7 GA error. It would be much more helpful if it told you what its actually expecting you to have in the "Code snippet (after)" field. Pull request coming shortly to do just that.
Thanks for your work.

### PR DESCRIPTION
**Pull request by NigelCunningham**
Make the D7 Google Analytics check more helpful by teaching it to tell you what it is looking for and what you have set at the moment.

### CODE REVIEW

**Comment by seanhamlin** [comment]
Hey @NigelCunningham, thanks for the PR!

If you can surround the code bits with `<code>` tags (and remove the quotes), I will merge this.

Current HTML output:

image

As a follow up commit, we could move the remediation into the remediation section.

**Comment by NigelCunningham** [comment]
Ah, I only saw text output. Is it okay having both the quotes and code tags? I guess ideally it should be code tags for html and quotes for plain text?

**Comment by seanhamlin** [comment]
Good question, I normally just use `<code>` tags (and no quotes), as the CLI output is nice to have, where as the HTML report is more-often-than-not client facing.

**Comment by seanhamlin** [comment]
Current issues:

* unbalanced HTML `<code>` tags
* remove quotes around code

I can fix this up as a follow up commit if you like.

**Comment by NigelCunningham** [comment]
Awww. Too much rush. Sorry.

**Comment by seanhamlin** [comment]
Thanks, patch is looking good. Will look at a follow up to implement the `remediate()` method.

**Pull request merged**
